### ISSUE TITLE
tab title does not change when file is renamed

### ISSUE THREAD

**Issue by tstack** [Textualize/toolong#10]
### Description

When a file is renamed, like when a file is rolled, the tab title does not update.

### How to reproduce

Open multiple files so there are tabs and then rename one of the files.  Note that the tab title does not change.

### Details

If the app is not going to follow files by name and continue to view ones that have been renamed/deleted, it should probably update the tab title accordingly.  (Note that keeping open a file that has been deleted will prevent the disk space from being reclaimed.)

**Comment by willmcgugan** [comment]
Presumably the user knows the filenames they opened, and changing the tabs after the app has started could only lead to confusion.

If you want to expand further on why you want this I am happy to listen,  but I'm afraid this is a wontfix.

**Comment by tstack** [comment]
> Presumably the user knows the filenames they opened

Yes, they opened "/var/log/messages" and when that file gets rolled over to "/var/log/messages.0" and a new "/var/log/messages" is created, folks will expect the display to reflect that accordingly.  That's why `tail` has the `-F`/`--follow=name` options.  And, when people open all the files with "/var/log/messages*", they're going to expect the display to reflect the current state of the world.  Tailing a deleted/renamed file is not the common case.
