### ISSUE TITLE
Pressing `/` when the find panel is visible closes it

### ISSUE THREAD

**Issue by tstack** [Textualize/toolong#11]
### How to reproduce

Open the find panel with `/` (or CTRL+F).  Press `TAB` to change the focus from the find input box to the "Case Sensitive" checkbox.  Press `/` again.

### Expected behavior

I kinda expect the input box to be focused again.

### Actual behavior

The find panel is closed.

**Comment by nurettn** [comment]
I tried to look at the problem. I think the FindDialog panel doesn't include the 'Case sensitive' and 'Regex' checkboxes, they appear as part of the main panel and the ctrl+f button becomes active when I focus on them.

**Comment by willmcgugan** [comment]
Thanks. Should be fixed in 1.1.1
