### ISSUE TITLE
Screen corruption viewing Help

### ISSUE THREAD

**Issue by gavinlaking** [Textualize/toolong#16]
Great project, looks pretty neat, however when you visit the Help page, the screen gets corrupted. I'm viewing a Rails log file which uses terminal escape sequences itself to format the view, so I wonder if that is messing with the output from toolong?

![image](https://github.com/Textualize/toolong/assets/282423/93eae629-9fc1-4867-ad1c-31aa9f31e41a)

**Comment by willmcgugan** [comment]
That's exactly what is happening. Toolong should really detect and handle escape sequences in logs.

**Comment by willmcgugan** [comment]
Thanks. Should be fixed in 1.1.1
