### ISSUE TITLE
using a non-existent file name with `-m` crashes with a traceback

### ISSUE THREAD

**Issue by tstack** [Textualize/toolong#20]
### Problem

Running `tl` in merge mode with a non-existent file path crashes with a traceback due to a `FileNotFoundError`

### How to reproduce

Run `tl` like so:

```
tl -m badname1 badname2
```

### Expected

When not in merge-mode, error notifications are popped up, so I would expect the same behavior.

**Comment by willmcgugan** [comment]
Thanks. Should be fixed in 1.1.1
