### ISSUE TITLE
text headers in log files should assume the timestamp of the first line with a timestamp when merging

### ISSUE THREAD

**Issue by tstack** [Textualize/toolong#24]
### Problem

When merging a file that starts with lines that do not have a timestamp, the lines show up at the bottom of the merged view (or not at all) instead of before the first line with a timestamp.

(For whatever reason, some log files do have textual headers.)

### How to reproduce

Create two files with the following contents:

```
This is a header
2023-03-12T23:16:52.071 Hello, World1!
2023-03-12T23:16:53.071 Hello, World2!
```

```
This is another header
2023-03-12T23:16:58.071 Hello, World3!
2023-03-12T23:16:59.071 Hello, World4!
```

Load them into `tl` with merging turned on.

### Expected

The header should be preserved and visible:

```
This is a header
2023-03-12T23:16:52.071 Hello, World1!
2023-03-12T23:16:53.071 Hello, World2!
This is another header
2023-03-12T23:16:58.071 Hello, World3!
2023-03-12T23:16:59.071 Hello, World4!
```

### Actual

This is what I'm seeing now:

<img width="285" alt="Screenshot 2024-02-13 at 7 08 34 AM" src="https://github.com/Textualize/toolong/assets/107532/c0d74407-3981-48ef-8b61-b37fa707e827">

The header text isn't being displayed.  Although, experimenting with other files, the header seemed to appear at the bottom of the view.  Not sure what the difference is...

**Comment by willmcgugan** [comment]
Thanks. Should be fixed in v1.2.1
