### ISSUE TITLE
Feature Request: add ability to export or save merged log files

### ISSUE THREAD

**Issue by myersg86** [Textualize/toolong#25]
## Context

`toolong` allows for merging multiple log files and sorting log entries in chronological order by auto detecting timestamps.

## What is the problem

Merged log files sorted in chronological order can't be exported, saved, or copy/pasted out of `toolong`

### Why is this a problem?

Very large, merged log files with many thousands or even millions of lines can be difficult to effectively parse or manage in the `toolong` TUI. In situations like this, it would be helpful to export or save the merged + sorted log file output so that one can use `grep`, `jq`, `awk`, `sed` and other tools for parsing the merged log file content.

## Proposal

Add the ability to export or save merged log file data from `toolong` to a local text file.

**Comment by willmcgugan** [comment]
Thanks. Should be fixed in 1.1.1

**Comment by myersg86** [comment]
Thank you so much @willmcgugan ! :bow:
