### ISSUE TITLE
/usr/lib/python3.11/site-packages/toolong/ui.py:68 in on_mount  

### ISSUE THREAD

**Issue by mfaridi1394** [Textualize/toolong#28]
Thanks guys,
this nice project.
I use manjaro and install your application by pamac and when I run for example 
`tl /var/log/boot.log`
I see something like this and I think it does not work

![Screenshot from 2024-02-14 14-41-47](https://github.com/Textualize/toolong/assets/32776227/083034d5-1139-4dd7-93c9-f55bdc45b574)

**Comment by willmcgugan** [comment]
It looks like you have an old version of Textual. If you install in to a virtual environement (or use pipx), you should get isolated dependancies.

**Comment by mfaridi1394** [comment]
> It looks like you have an old version of Textual. If you install in to a virtual environement (or use pipx), you should get isolated dependancies.

Thank,
I install this great application by pip and everything work like charm.

**Comment by mfaridi1394** [comment]
after install by pip my problem solved.
