### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by nzsmith1** [Textualize/toolong#3]
First off - thank you for this project and your others (we use Textual a lot!)

Having some issues using this in Windows, not sure if Windows is supposed to be supported or not.

**Installation:**
- pipx 1.4.3
- Windows 11
- Python 3.11.2

**Issues so far:**
- mmap.mmap call is a little different on Windows or atleast on my machine?
Had to change `prot=mmap.PROT_READ` to `access=mmap.ACCESS_READ` - found this error here: https://github.com/mvt-project/mvt/issues/61

Now I am getting - `AttributeError: module 'os' has no attribute 'pread'`

It is unclear to me how I can edit this to work on Windows because I am not confident I understand what you are doing here with os.preread

- Cheers

**Comment by willmcgugan** [comment]
It doesn't run on Windows yet. I've updated the README.

The file watcher will also need updating. It uses the selectors API which only works with sockets on Windows.

It will be a little work for Windows, but it is coming.

**Comment by willmcgugan** [comment]
Toolong runs on Windows from 1.2.0 onwards...
