### ISSUE TITLE
Slow search?

### ISSUE THREAD

**Issue by olejorgenb** [Textualize/toolong#32]
Hi, I really appreciate efforts to create better tools for investigating logs!

But, the search is very slow on large log files? `grep` processes a 2M lines long 400MB log file in ~250ms while `toolong` spends too long time to measure to completion :/

**Comment by willmcgugan** [comment]
There was a bug in search, fixed in v1.1.3. It's never going to be quite as fas as a dedicated tool.

**Comment by olejorgenb** [comment]
Nice. For some reason pip installed 1.1.1 :thinking:  (or maybe I've installed it earlier and a new `pip install` doesn't update)

I didn't mean to imply that I expected the search to be as fast as `grep` :) Just to provide a baseline. 

1.1.3 is fully usable :+1: 

(love the advance-by-time functionality!)
