### ISSUE TITLE
Cannot follow with tail

### ISSUE THREAD

**Issue by adrfantini** [Textualize/toolong#36]
My `tl`, installed via AUR on Arch, cannot seem to be able to `tail` files.

My test setup:
- on one terminal, `while true; do date >> test.log; sleep 1s; done`
- on another terminal, `tl test.log`. It is stationary, even if `CTRL+T` is selected and the `TAIL` indicator is present on the bottom right.

Any idea why?

**Comment by willmcgugan** [comment]
Thanks. Fixed in v1.2.2
