### ISSUE TITLE
Pipe Support

### ISSUE THREAD

**Issue by jtrip** [Textualize/toolong#4]
Hello, toolong looks very nice in my quick testing, thanks for making it!

The mentions of `tail` and `less` in the readme got me excited to try to use it as a pager for journalctl but that doesn't seem to work. In fact piping any text to it doesn't seem to work.

if I set:
`export SYSTEMD_PAGER=/home/me/.local/bin/tl`
and then run `journalctl`, I get the tl help output

also if I just pipe text from journalctl or cat I get the tl help output.

Thanks for reading!

**Comment by Tinche** [comment]
I was just about to make this issue. Would love to be able to pipe `kubectl logs -f` or `stern` into toolong.

**Comment by gennaro-tedesco** [comment]
I second this use case as well: I have tried this out on `kubectl` logs and unfortunately being unable to read from pipes reduces the cases where this can be used a lot. Hopefully this feature to come in soon!

**Comment by pawamoy** [comment]
And `tl <(journalctl)` fails with "Illegal seek" :smile:

**Comment by seal2001** [comment]
That well fix it you can uninstall the pipe again install the pipe plugins

**Comment by MichaelXavier** [comment]
> That well fix it you can uninstall the pipe again install the pipe plugins

I don't understand what you're referring to.
