### ISSUE TITLE
Fix blank canvas when reading file with a very long line

### ISSUE THREAD

**Issue by ketozhang** [Textualize/toolong#41]
I have a unformatted JSON file that is one very long line. toolong either gives me a blank canvas or the entire screen is blank.

I understand that toolong is not intended to be used with files like this—you should probably use `less`. I'm asking for a more informative screen that tells me toolong can't handle it, so I can try something else (e.g., `cat long.json | jq | toolong`)

**Comment by willmcgugan** [comment]
Please try v1.4.0
